# Site settings
title: global.opennic
site: global.project
description: > # this means to ignore newlines until "baseurl:"
    An organization of hobbyists who run an alternative DNS network,
    also provides access to domains not administered by ICANN.
baseurl: ""
url: "https://www.opennic.org"
include: ["_redirects", ".well-known"]
paginate: 5
paginate_path: "/page:num/"
languages: ["en"]
color:
    main: "black"
    navbar: "white"
    chips: "blue"
    footer: "grey"
owner:
    email:
    facebook:
        show: false
        name: "none"
        url: "https://fb.me/none"
    github:
        show: true
        username: "OpenNIC"
    twitter:
        show: true
        username: "OpenNIC"
    disqus:
        show: false
        username: "jonaharagon"
sass:
    sass_dir: _sass
    style: compressed
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-multiple-languages-plugin
